apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joinedcluster-role
rules:
- apiGroups:
  - clustermanager.onprem.openshift.io
  resources:
  - 'joinedclusters/status'
  verbs:
  - update
