apiVersion: v1
kind: ServiceAccount
metadata:
  name: onprem-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: onprem-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - onprem-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - onprem.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onprem-operator
subjects:
- kind: ServiceAccount
  name: onprem-operator
roleRef:
  kind: Role
  name: onprem-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onprem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onprem-operator
  template:
    metadata:
      labels:
        name: onprem-operator
    spec:
      serviceAccountName: onprem-operator
      containers:
        - name: onprem-operator
          image: quay.io/sohankunkerkar/onprem-operator:latest
          command:
          - onprem-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onprem-operator"
---
