apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-prem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: on-prem-operator
  template:
    metadata:
      labels:
        name: on-prem-operator
    spec:
      serviceAccountName: on-prem-operator
      containers:
        - name: on-prem-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - on-prem-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "on-prem-operator"
