apiVersion: apps/v1
kind: Deployment
metadata:
  name: onprem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onprem-operator
  template:
    metadata:
      labels:
        name: onprem-operator
    spec:
      serviceAccountName: onprem-operator
      containers:
        - name: onprem-operator
          # Replace this with the built image name
          image: quay.io/sohankunkerkar/onprem-operator:latest
          command:
          - onprem-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onprem-operator"
